baseURL = 'https://www.yojnaportal.com/'
languageCode = 'en-US'
title = 'YOJNA PORTAL'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
description = "Stay updated with the latest government schemes, Sarkari Yojna news, and policy updates on Yojna Portal."
paginate = 20
logo = "logo/logo-100x100.png"
cssStyle = "css/main/scheme.css"
jsFile = "js/main/default.js"
adminMode = true
 version = "3.3.21"

[sitemap]
  filename = "sitemap.xml"
  changefreq = "daily"
  priority = 0.5

  