name: Deploy Hugo site to CF Pages every 24 hours

on:
  schedule:
      - cron: "30 3 * * *" # रोज़ाना 9:00 AM IST (03:30 UTC)
  workflow_dispatch:       # Manual run option

concurrency:
  group: cloudflare-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Publish to Cloudflare Pages (with retry)
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            npx wrangler@2 pages deploy ./public \
              --project-name ${{ secrets.CF_PROJECT_NAME }} \
              --account-id ${{ secrets.CF_ACCOUNT_ID }} \
              --api-token ${{ secrets.CF_API_TOKEN }}
